### ISSUE TITLE
[Enhancement] Process links on all games

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extension-LinkUtilities#30]
Unless I'm missed the option elsewhere, the user has to manually edit each game to run sort/remove/rename/dedupe.

Options in Playnite menu > Extensions > Link Utilities to run this on all games (each action separately, or all at once) would help.

Thanks.

**Comment by HerrKnarz** [comment]
When you select more than one game the addon goes through all selected ones. But I could also add a button to the extensions menu for all filtered games or the whole library, I guess. That way you won't need to select them all beforehand. I myself like to do it in smaller doses though, because depending on the website it takes some time to add all the links.

**Comment by chocolatechipcats** [comment]
Ah yeah, I forgot about adding— and with entire libraries I suppose there's the risk of making the sites angry enough to rate-limit or block.

**Comment by HerrKnarz** [comment]
I added extension main menu items for all cleaning actions for filtered and all games. There's also a new button "clean up" in the main and game menus to do all those actions at once. The feature will be available with version 1.8!
